
  CREATE UNIQUE INDEX "LLANTAS"."KMRL_LLAN_GRU_FEC_PK" ON "LLANTAS"."KMS_RECORRIDO_LLANTAS" ("KMRL_SECUENCIA_NB", "KMRL_LLANTA_NB", "KMRL_GRUPO_CH") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_APEX_KROW" ON "LLANTAS"."APEX_KROW" ("SECUENCIA") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_BAJA_LLANTA" ON "LLANTAS"."BAJA" ("LLANTA") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_CLASES_CODIGO" ON "LLANTAS"."CLASES" ("CODIGO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_FICHATEC_CODIGO" ON "LLANTAS"."FICHATEC" ("CODIGO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_HISTOMUES" ON "LLANTAS"."HISTOMUES" ("LLANTA", "GRUPO", "KILOM", "FECHA") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_HISTORIA_LLANGRU" ON "LLANTAS"."HISTORIA" ("LLANTA", "GRUPO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_INTERMEDIO_LLANGRU" ON "LLANTAS"."INTERMEDIO" ("LLANTA", "GRUPO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_INVENTARIO_LLANGRU" ON "LLANTAS"."INVENTARIO" ("LLANTA", "GRUPO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_LLANTAS_LLANGRU" ON "LLANTAS"."LLANTAS" ("LLANTA", "GRUPO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_LOCALIZA_CODIGO" ON "LLANTAS"."LOCALIZA" ("CODIGO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_MARCA_CODIGO" ON "LLANTAS"."MARCAS_LLANTAS" ("CODIGO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_MUESTRE_LLANGRU" ON "LLANTAS"."MUESTREO" ("LLANTA", "GRUPO", "KILOM") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_NEUMATICO_CODIGO" ON "LLANTAS"."NEUMATICO" ("CODIGO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_OBSERVA_CODIGO" ON "LLANTAS"."OBSERVA" ("CODIGO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_PROVEEDORES_CODIGO" ON "LLANTAS"."PROVEEDORES_LLANTAS" ("CODIGO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_REFERENCIA_CODIGO" ON "LLANTAS"."REFERENCIA" ("CODIGO") 

;

  CREATE UNIQUE INDEX "LLANTAS"."PK_RETIRADAS_LLANGRU" ON "LLANTAS"."RETIRADAS" ("LLANTA", "GRUPO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_SECLOGLLANTAS" ON "LLANTAS"."LOG_LLANTAS" ("LOGL_SECUENCIA_NB") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_SECUENCIA" ON "LLANTAS"."REPORTE_LLANTAS" ("SECUENCIA") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_TIPOS_CODIGO" ON "LLANTAS"."TIPOS" ("CODIGO") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_TIPVEHRES" ON "LLANTAS"."TIPVEHRES" ("REFR") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_TMPLOGLLA" ON "LLANTAS"."TMPLOGLLA" ("SECUENCIA") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_TMPLOGMOV" ON "LLANTAS"."TMPLOGMOV" ("SECUENCIA") 
;

  CREATE UNIQUE INDEX "LLANTAS"."PK_VEHICULOS_PLACA" ON "LLANTAS"."VEHICULOS_LLANTAS" ("PLACA") 
;

  CREATE UNIQUE INDEX "LLANTAS"."UK_VEHI_POS" ON "LLANTAS"."LLANTAS" ("VEHICULO", "POSICION") 
;


