  CREATE TABLE LLANTAS.AUDITA 
(	USUARIO VARCHAR2(20), 
	OPCION VARCHAR2(4), 
	FECHA DATE, 
	NUMERO VARCHAR2(20), 
	TABLA VARCHAR2(12)
);
COMMENT ON TABLE LLANTAS.AUDITA IS 'Información de Auditoría de la aplicación';

  CREATE TABLE LLANTAS.BAJA 
(	LLANTA VARCHAR2(20), 
	GRUPO CHAR(3), 
	FECHA DATE, 
	FICHA NUMBER(5,0), 
	QUIEN VARCHAR2(10), 
	 CONSTRAINT PK_BAJA_LLANTA PRIMARY KEY (LLANTA)
);
COMMENT ON TABLE LLANTAS.BAJA IS 'Registro de llantas dadas de baja';

  CREATE TABLE LLANTAS.CLASES 
(	CODIGO NUMBER(2,0), 
	NOMBRE VARCHAR2(15) CONSTRAINT NN_CLASES_NOMBRE NOT NULL ENABLE, 
	NUMERO NUMBER(2,0), 
	CATEGORIA CHAR(1), 
	 CONSTRAINT PK_CLASES_CODIGO PRIMARY KEY (CODIGO)
);
COMMENT ON TABLE LLANTAS.CLASES IS 'Almacena las clases de vehículos que tiene la Compañía';

  CREATE TABLE LLANTAS.FICHATEC 
(	CODIGO NUMBER(5,0), 
	MARCA NUMBER(2,0) CONSTRAINT NN_FICHATEC_MARCA NOT NULL ENABLE, 
	TIPO NUMBER(2,0) CONSTRAINT NN_FICHATEC_TIPO NOT NULL ENABLE, 
	REF NUMBER(5,0) CONSTRAINT NN_FICHATEC_REF NOT NULL ENABLE, 
	DIMENSION VARCHAR2(8), 
	KESPERA NUMBER(6,0) CONSTRAINT NN_FICHATEC_KESPERA NOT NULL ENABLE, 
	KMAYOR NUMBER(5,0), 
	KMENOR NUMBER(5,0), 
	KMEDIO NUMBER(5,0), 
	RESPERA NUMBER(1,0), 
	PERDIDA NUMBER(4,0), 
	TOTOAL NUMBER(6,0), 
	COSTOH NUMBER(7,2), 
	PI NUMBER(3,1) CONSTRAINT NN_FICHATEC_PI NOT NULL ENABLE, 
	PC NUMBER(3,1) CONSTRAINT NN_FICHATEC_PC NOT NULL ENABLE, 
	PD NUMBER(3,1) CONSTRAINT NN_FICHATEC_PD NOT NULL ENABLE, 
	UCOMPRA NUMBER(4,0), 
	UPRECIO NUMBER(14,4), 
	UFECHA DATE, 
	PROVEE1 NUMBER(5,0) CONSTRAINT NN_FICHATEC_PROVEE1 NOT NULL ENABLE, 
	PROVEE2 NUMBER(5,0) CONSTRAINT NN_FICHATEC_PROVEE2 NOT NULL ENABLE, 
	PROVEEU NUMBER(5,0) CONSTRAINT NN_FICHATEC_PROVEEU NOT NULL ENABLE, 
	PESO NUMBER(4,0), 
	 CONSTRAINT PK_FICHATEC_CODIGO PRIMARY KEY (CODIGO)
);
COMMENT ON TABLE LLANTAS.FICHATEC IS 'Almacena las fichas técnicas de las llantas';

  CREATE TABLE LLANTAS.HISTOMUES 
(	LLANTA VARCHAR2(20), 
	GRUPO CHAR(3), 
	KILOM NUMBER(8,0), 
	PI NUMBER(2,0), 
	PC NUMBER(2,0), 
	PD NUMBER(2,0), 
	PRESION NUMBER(3,0), 
	FECHA DATE, 
	 CONSTRAINT PK_HISTOMUES PRIMARY KEY (LLANTA, GRUPO, KILOM, FECHA)
);
COMMENT ON TABLE LLANTAS.HISTOMUES IS 'Almacena el histórico de los muestreos';

  CREATE TABLE LLANTAS.HISTORIA 
(	LLANTA VARCHAR2(20), 
	GRUPO CHAR(3), 
	VALOR NUMBER(7,0) CONSTRAINT NN_HISTORIA_VALOR NOT NULL ENABLE, 
	FECHA DATE CONSTRAINT NN_HISTORIA_FECHA NOT NULL ENABLE, 
	PROVEE NUMBER(5,0) CONSTRAINT NN_HISTORIA_PROVEE NOT NULL ENABLE, 
	FACTURA NUMBER(7,0) CONSTRAINT NN_HISTORIA_FACTURA NOT NULL ENABLE, 
	FICHA NUMBER(5,0) CONSTRAINT NN_HISTORIA_FICHA NOT NULL ENABLE, 
	NEUMA NUMBER(2,0), 
	VALORRN NUMBER(7,0), 
	PROTEC NUMBER(2,0), 
	VALORP NUMBER(7,0), 
	VEHICULO CHAR(6) CONSTRAINT NN_HISTORIA_VEHICULO NOT NULL ENABLE, 
	POSICION NUMBER(2,0) CONSTRAINT NN_HISTORIA_POSICION NOT NULL ENABLE, 
	KINSTALA NUMBER(8,0) CONSTRAINT NN_HISTORIA_KINSTALA NOT NULL ENABLE, 
	FECHAI DATE CONSTRAINT NN_HISTORIA_FECHAI NOT NULL ENABLE, 
	KREMUEVE NUMBER(8,0) CONSTRAINT NN_HISTORIA_KREMUEVE NOT NULL ENABLE, 
	FECHAF DATE CONSTRAINT NN_HISTORIA_FECHAF NOT NULL ENABLE, 
	PORQUE NUMBER(3,0) CONSTRAINT NN_HISTORIA_PORQUE NOT NULL ENABLE, 
	 CONSTRAINT PK_HISTORIA_LLANGRU PRIMARY KEY (LLANTA, GRUPO) ENABLE, 
	 CONSTRAINT FK_HISTORIA_FICHA FOREIGN KEY (FICHA) REFERENCES LLANTAS.FICHATEC (CODIGO) ENABLE, 
	 CONSTRAINT FK_HIST_POR_OBS_COD FOREIGN KEY (PORQUE) REFERENCES LLANTAS.OBSERVA (CODIGO) ENABLE
);
COMMENT ON TABLE LLANTAS.HISTORIA IS 'Almacena la vida histórica de cada llanta, de acuerdo a los vehículos en donde se ha subido y se ha desmontado respectivamente';

  CREATE TABLE LLANTAS.HISTORIAN 
(	CODIGO NUMBER(4,0), 
	CUALES NUMBER(1,0), 
	CANTI NUMBER(4,0), 
	VALORU NUMBER(6,0), 
	FECHA DATE, 
	PROVE NUMBER(5,0), 
	FACTURA NUMBER(7,0), 
	MARCA NUMBER(2,0)
);

  CREATE TABLE LLANTAS.INTERMEDIO 
(	LLANTA VARCHAR2(20), 
	GRUPO CHAR(3), 
	ESTADO NUMBER(2,0), 
	PROVE NUMBER(5,0), 
	FICHA NUMBER(5,0), 
	 CONSTRAINT PK_INTERMEDIO_LLANGRU PRIMARY KEY (LLANTA, GRUPO) ENABLE, 
	 CONSTRAINT FK_INTERMEDIO_FICHA FOREIGN KEY (FICHA) REFERENCES LLANTAS.FICHATEC (CODIGO) ENABLE
);
COMMENT ON TABLE LLANTAS.INTERMEDIO IS 'Almacena las llantas que estan listas para recircular';

  CREATE TABLE LLANTAS.INVENTARIO 
(	LLANTA VARCHAR2(20), 
	GRUPO CHAR(3), 
	INVENT NUMBER(2,0) CONSTRAINT NN_NVENTARIO_INVENT NOT NULL ENABLE, 
	VALOR NUMBER(7,0) CONSTRAINT NN_INVENTARIO_VALOR NOT NULL ENABLE, 
	FECHA DATE CONSTRAINT NN_INVENTARIO_FECHA NOT NULL ENABLE, 
	PROVE NUMBER(5,0) CONSTRAINT NN_NVENTARIO_PROVE NOT NULL ENABLE, 
	FACTURA NUMBER(7,0) CONSTRAINT NN_INVENTARIO_FACTURA NOT NULL ENABLE, 
	FICHA NUMBER(5,0) CONSTRAINT NN_NVENTARIO_FICHA NOT NULL ENABLE, 
	 CONSTRAINT PK_INVENTARIO_LLANGRU PRIMARY KEY (LLANTA, GRUPO) ENABLE, 
	 CONSTRAINT FK_INVENTARIO_FICHA FOREIGN KEY (FICHA) REFERENCES LLANTAS.FICHATEC (CODIGO) ENABLE, 
	 CONSTRAINT FK_INVENTARIO_INVENT FOREIGN KEY (INVENT) REFERENCES LLANTAS.LOCALIZA (CODIGO) ENABLE
);
COMMENT ON TABLE LLANTAS.INVENTARIO IS 'Almacen las llantas que se encuentran en inventario y que no han sido montadas en ningún vehículo';

  CREATE TABLE LLANTAS.KMS_RECORRIDO_LLANTAS 
   (	KMRL_SECUENCIA_NB NUMBER(10,0) NOT NULL ENABLE, 
	KMRL_LLANTA_NB VARCHAR2(20), 
	KMRL_GRUPO_CH CHAR(3) NOT NULL ENABLE, 
	KMRL_KMSRECORRIDO_NB NUMBER(14,4) NOT NULL ENABLE, 
	KMRL_FECHA_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT KMRL_LLAN_GRU_FEC_PK PRIMARY KEY (KMRL_SECUENCIA_NB, KMRL_LLANTA_NB, KMRL_GRUPO_CH) ENABLE
);

  CREATE TABLE LLANTAS.LLANTAS 
(	LLANTA VARCHAR2(20), 
	GRUPO CHAR(3), 
	VALOR NUMBER(7,0) CONSTRAINT NN_LLANTAS_VALOR NOT NULL ENABLE, 
	FECHA DATE CONSTRAINT NN_LLANTAS_FECHA NOT NULL ENABLE, 
	PROVEE NUMBER(5,0) CONSTRAINT NN_LLANTAS_PROVEE NOT NULL ENABLE, 
	FACTURA NUMBER(7,0) CONSTRAINT NN_LLANTAS_FACTURA NOT NULL ENABLE, 
	FICHA NUMBER(5,0) CONSTRAINT NN_LLANTAS_FICHA NOT NULL ENABLE, 
	NEUMA NUMBER(2,0), 
	VALORRN NUMBER(7,0), 
	PROTEC NUMBER(2,0), 
	VALORP NUMBER(7,0), 
	VEHICULO CHAR(6) CONSTRAINT NN_LLANTAS_VEHICULO NOT NULL ENABLE, 
	POSICION NUMBER(2,0) CONSTRAINT NN_LLANTAS_POSICION NOT NULL ENABLE, 
	KINSTALA NUMBER(8,0) CONSTRAINT NN_LLANTAS_KINSTALA NOT NULL ENABLE, 
	FECHAI DATE CONSTRAINT NN_LLANTAS_FECHAI NOT NULL ENABLE, 
	 CONSTRAINT PK_LLANTAS_LLANGRU PRIMARY KEY (LLANTA, GRUPO) ENABLE, 
	 CONSTRAINT UK_VEHI_POS UNIQUE (VEHICULO, POSICION) ENABLE, 
	 CONSTRAINT FK_LLANTAS_FICHA FOREIGN KEY (FICHA) REFERENCES LLANTAS.FICHATEC (CODIGO) ENABLE, 
	 CONSTRAINT FK_VEHICULO_VEHILLANTAS FOREIGN KEY (VEHICULO) REFERENCES LLANTAS.VEHICULOS_LLANTAS (PLACA) ENABLE
);
COMMENT ON TABLE LLANTAS.LLANTAS IS 'Almacena las llantas actuales instaladas en un vehículo o trailer';

  CREATE TABLE LLANTAS.LOCALIZA 
(	CODIGO NUMBER(2,0), 
	NOMBRE VARCHAR2(15) CONSTRAINT NN_LOCALIZA_NOMBRE NOT NULL ENABLE, 
	 CONSTRAINT PK_LOCALIZA_CODIGO PRIMARY KEY (CODIGO) ENABLE
);

  CREATE TABLE LLANTAS.LOG_LLANTAS 
(	LOGL_SECUENCIA_NB NUMBER(10,0) NOT NULL ENABLE, 
	LOGL_MENSAJE_V2 VARCHAR2(2000) NOT NULL ENABLE, 
	LOGL_FECHA_DT DATE NOT NULL ENABLE, 
	 CONSTRAINT PK_SECLOGLLANTAS PRIMARY KEY (LOGL_SECUENCIA_NB) ENABLE
);

  CREATE TABLE LLANTAS.MARCAS_LLANTAS 
(	CODIGO NUMBER(2,0), 
	NOMBRE VARCHAR2(15) NOT NULL ENABLE, 
	 CONSTRAINT PK_MARCA_CODIGO PRIMARY KEY (CODIGO) ENABLE
);
COMMENT ON TABLE LLANTAS.MARCAS_LLANTAS IS 'Almacena todas las marcas de llantas que trabaja la Compañía';

  CREATE TABLE LLANTAS.MUESTREO 
(	LLANTA VARCHAR2(20), 
	GRUPO CHAR(3), 
	KILOM NUMBER(8,0), 
	PI NUMBER(3,1) CONSTRAINT NN_MUESTREO_PI1 NOT NULL ENABLE, 
	PC NUMBER(3,1) CONSTRAINT NN_MUESTREO_PC1 NOT NULL ENABLE, 
	PD NUMBER(3,1) CONSTRAINT NN_MUESTREO_PD1 NOT NULL ENABLE, 
	PRESION NUMBER(3,0) CONSTRAINT NN_MUESTREO_PRESION1 NOT NULL ENABLE, 
	FECHA DATE CONSTRAINT NN_MUESTREO_FECHA1 NOT NULL ENABLE, 
	 CONSTRAINT PK_MUESTRE_LLANGRU PRIMARY KEY (LLANTA, GRUPO, KILOM) ENABLE
);
COMMENT ON TABLE LLANTAS.MUESTREO IS 'Almacena los muestreo realizados a cada una de las llantas';

  CREATE TABLE LLANTAS.NEUMATICO 
(	CODIGO NUMBER(4,0), 
	CUALES NUMBER(1,0) CONSTRAINT NN_NEUMATICO_CUALES NOT NULL ENABLE, 
	CANTI NUMBER(4,0) CONSTRAINT NN_NEUMATICO_CANTI NOT NULL ENABLE, 
	CANACT NUMBER(4,0), 
	VALORU NUMBER(6,0) CONSTRAINT NN_NEUMATICO_VALORU NOT NULL ENABLE, 
	FECHA DATE CONSTRAINT NN_NEUMATICO_FECHA NOT NULL ENABLE, 
	PROVE NUMBER(5,0) CONSTRAINT NN_NEUMATICO_PROVE NOT NULL ENABLE, 
	FACTURA NUMBER(7,0) CONSTRAINT NN_NEUMATICO_FACTURA NOT NULL ENABLE, 
	MARCA NUMBER(2,0) CONSTRAINT NN_NEUMATICO_MARCA NOT NULL ENABLE, 
	 CONSTRAINT PK_NEUMATICO_CODIGO PRIMARY KEY (CODIGO) ENABLE, 
	 CONSTRAINT FK_NEUMATICO_MARCA FOREIGN KEY (MARCA) REFERENCES LLANTAS.MARCAS_LLANTAS (CODIGO) ENABLE
);

  CREATE TABLE LLANTAS.OBSERVA 
(	CODIGO NUMBER(3,0), 
	DETALLE VARCHAR2(50) CONSTRAINT NN_OBSERVA_DETALLE NOT NULL ENABLE, 
	ENTRA CHAR(1) CONSTRAINT NN_OBSERVA_ENTRA NOT NULL ENABLE, 
	 CONSTRAINT PK_OBSERVA_CODIGO PRIMARY KEY (CODIGO) ENABLE
);
COMMENT ON TABLE LLANTAS.OBSERVA IS 'Almacena las observaciones de baja de las llantas';

  CREATE TABLE LLANTAS.PROVEEDORES_LLANTAS 
(	CODIGO NUMBER(5,0), 
	NOMBRE VARCHAR2(40) NOT NULL ENABLE, 
	NIT NUMBER(9,0) NOT NULL ENABLE, 
	DIRECCION VARCHAR2(30), 
	TELEFONO NUMBER(10,0), 
	CONTACTO VARCHAR2(40), 
	PAGO NUMBER(3,0) NOT NULL ENABLE, 
	CODMILENIO NUMBER(5,0), 
	 CONSTRAINT PK_PROVEEDORES_CODIGO PRIMARY KEY (CODIGO) ENABLE
);

  CREATE TABLE LLANTAS.REFERENCIA 
(	CODIGO NUMBER(5,0), 
	NOMBRE VARCHAR2(15) CONSTRAINT NN_REFERENCIA_NOMBRE NOT NULL ENABLE, 
	 CONSTRAINT PK_REFERENCIA_CODIGO PRIMARY KEY (CODIGO) ENABLE
);

  CREATE TABLE LLANTAS.REPORTE_LLANTAS 
(	SECUENCIA NUMBER(10,0) NOT NULL ENABLE, 
	LLANTA VARCHAR2(20) NOT NULL ENABLE, 
	GRUPO CHAR(3) NOT NULL ENABLE, 
	FICHA NUMBER(5,0) NOT NULL ENABLE, 
	MARCA NUMBER(2,0) NOT NULL ENABLE, 
	REFERENCIA NUMBER(5,0) NOT NULL ENABLE, 
	DIMENSION VARCHAR2(8) NOT NULL ENABLE, 
	KINSTALA NUMBER(12,2), 
	KMUESTREO NUMBER(12,2), 
	KRECORRIDO NUMBER(12,2) NOT NULL ENABLE, 
	KPORRECORRER NUMBER(12,2), 
	KTOTPROYECTADO NUMBER(12,2), 
	FECHABAJAPROY DATE, 
	 CONSTRAINT PK_SECUENCIA PRIMARY KEY (SECUENCIA) ENABLE
);

  CREATE TABLE LLANTAS.RETIRADAS 
(	LLANTA VARCHAR2(20), 
	GRUPO CHAR(3) NOT NULL ENABLE, 
	VALOR NUMBER(6,0) NOT NULL ENABLE, 
	ACTA NUMBER(5,0) NOT NULL ENABLE, 
	FECHA DATE DEFAULT SYSDATE, 
	AUTOR VARCHAR2(25) NOT NULL ENABLE, 
	OBSER NUMBER(3,0), 
	FICHA NUMBER(5,0), 
	PORQUE NUMBER(3,0), 
	 CONSTRAINT PK_RETIRADAS_LLANGRU PRIMARY KEY (LLANTA, GRUPO) ENABLE, 
	 CONSTRAINT FK_RETIRADAS_FICHA FOREIGN KEY (FICHA)
	  REFERENCES LLANTAS.FICHATEC (CODIGO) ENABLE, 
	 CONSTRAINT FK_RETIRADAS_OBSER FOREIGN KEY (OBSER)
	  REFERENCES LLANTAS.OBSERVA (CODIGO) ENABLE, 
	 CONSTRAINT RETI_PORQ_OBSE_COD_FK FOREIGN KEY (PORQUE)
	  REFERENCES LLANTAS.OBSERVA (CODIGO) ENABLE
);
COMMENT ON TABLE LLANTAS.RETIRADAS IS 'Almacena las llantas que se han dado de baja';

  CREATE TABLE LLANTAS.TIPOS 
(	CODIGO NUMBER(2,0), 
	NOMBRE VARCHAR2(15) CONSTRAINT NN_TIPOS_NOMBRE NOT NULL ENABLE, 
	 CONSTRAINT PK_TIPOS_CODIGO PRIMARY KEY (CODIGO) ENABLE
);
COMMENT ON TABLE LLANTAS.TIPOS IS 'Almacen los tipos de llantas que maneja la Compañía';

  CREATE TABLE LLANTAS.TIPVEHRES 
(	MARR VARCHAR2(15), 
	REFR VARCHAR2(15), 
	NUERC NUMBER(9,0), 
	PRIRC NUMBER(9,0), 
	SEGRC NUMBER(9,0), 
	TERRC NUMBER(9,0), 
	CUARC NUMBER(9,0), 
	QUIRC NUMBER(9,0), 
	GALRC NUMBER(9,0), 
	TOTRC NUMBER(9,0), 
	NUERT NUMBER(9,0), 
	PRIRT NUMBER(9,0), 
	SEGRT NUMBER(9,0), 
	TERRT NUMBER(9,0), 
	CUART NUMBER(9,0), 
	QUIRT NUMBER(9,0), 
	GALRT NUMBER(9,0), 
	TOTRT NUMBER(9,0), 
	GTCT NUMBER(10,0), 
	 CONSTRAINT PK_TIPVEHRES PRIMARY KEY (REFR) ENABLE
);

  CREATE TABLE LLANTAS.TMPLOGLLA 
(	SECUENCIA NUMBER(7,0) NOT NULL ENABLE, 
	MOVIMIENTOS VARCHAR2(4000), 
	FECHA DATE DEFAULT sysdate, 
	 CONSTRAINT PK_TMPLOGLLA PRIMARY KEY (SECUENCIA) ENABLE
);

  CREATE TABLE LLANTAS.TMPLOGMOV 
(	SECUENCIA NUMBER(7,0), 
	TICKET NUMBER(7,0), 
	LOGMOV VARCHAR2(4000), 
	PLACA VARCHAR2(6), 
	KLMS NUMBER(7,0), 
	ESTADO VARCHAR2(1), 
	USUARIO NUMBER(13,0), 
	OFICINA NUMBER(3,0), 
	FECHA DATE DEFAULT sysdate, 
	 CONSTRAINT PK_TMPLOGMOV PRIMARY KEY (SECUENCIA) ENABLE
);

  CREATE TABLE LLANTAS.VEHICULOS_LLANTAS 
(	PLACA CHAR(6), 
	CLASE NUMBER(2,0) NOT NULL ENABLE, 
	MARCA VARCHAR2(15) NOT NULL ENABLE, 
	MODELO NUMBER(4,0) NOT NULL ENABLE, 
	KILOMINI NUMBER(7,0) NOT NULL ENABLE, 
	KILOMACT NUMBER(7,0) NOT NULL ENABLE, 
	ESTADO VARCHAR2(1) NOT NULL ENABLE, 
	OPERANDO VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT PK_VEHICULOS_PLACA PRIMARY KEY (PLACA) ENABLE, 
	 CONSTRAINT FK_VEHICULOS_CLASE FOREIGN KEY (CLASE) REFERENCES LLANTAS.CLASES (CODIGO) ENABLE
);
COMMENT ON TABLE LLANTAS.VEHICULOS_LLANTAS IS 'Almacena todos los vehículos de la Compañía';

  CREATE TABLE LLANTAS.VIDAK 
(	LLANTA VARCHAR2(20), 
	GRUPO CHAR(3), 
	VEHICULO CHAR(6), 
	REF NUMBER(5,0), 
	PI NUMBER(4,2), 
	PC NUMBER(4,2), 
	PD NUMBER(4,2), 
	KACTUAL NUMBER(8,0), 
	KRECO NUMBER(8,0), 
	KM_MM NUMBER(11,0), 
	VIDAES NUMBER(8,0), 
	KILCAM NUMBER(8,0), 
	DACTUAL DATE, 
	DRECO NUMBER(8,0), 
	DM_MM NUMBER(11,0), 
	VIDAESD NUMBER(8,0), 
	DIACAM DATE, 
	POSICION NUMBER(2,0), 
	VIDARE NUMBER(8,0), 
	VIDARED NUMBER(8,0)
);

-- LLANTAS.V_CONSUMOS_LLANTAS source

CREATE OR REPLACE FORCE VIEW "LLANTAS"."V_CONSUMOS_LLANTAS" ("ANO", "MES", "TOTAL") AS 
  SELECT SUBSTR(TO_CHAR(a.fecha,'dd/mm/rrrr'),7,4) ano,  
DECODE(SUBSTR(TO_CHAR(a.fecha,'dd/mm/rrrr'),4,2), 
'01','ENERO', 
'02','FEBRERO', 
'03','MARZO', 
'04','ABRIL', 
'05','MAYO', 
'06','JUNIO', 
'07','JULIO', 
'08','AGOSTO', 
'09','SEPTIEMBRE', 
'10','OCTUBRE', 
'11','NOVIEMBRE', 
'12','DICIEMBRE') MES,  
NVL(COUNT(*),0) TOTAL 
FROM historia a 
WHERE a.grupo = '000' 
AND (a.llanta, a.grupo) NOT IN (SELECT llanta, grupo FROM llantas) 
GROUP BY SUBSTR(TO_CHAR(a.fecha,'dd/mm/rrrr'),7,4),SUBSTR(TO_CHAR(a.fecha,'dd/mm/rrrr'),4,2) 
UNION 
SELECT SUBSTR(TO_CHAR(fecha,'dd/mm/rrrr'),7,4) ano,  
DECODE(SUBSTR(TO_CHAR(fecha,'dd/mm/rrrr'),4,2), 
'01','ENERO', 
'02','FEBRERO', 
'03','MARZO', 
'04','ABRIL', 
'05','MAYO', 
'06','JUNIO', 
'07','JULIO', 
'08','AGOSTO', 
'09','SEPTIEMBRE', 
'10','OCTUBRE', 
'11','NOVIEMBRE', 
'12','DICIEMBRE') MES,  
NVL(COUNT(*),0) TOTAL 
FROM llantas 
WHERE grupo = '000' 
GROUP BY SUBSTR(TO_CHAR(fecha,'dd/mm/rrrr'),7,4),SUBSTR(TO_CHAR(fecha,'dd/mm/rrrr'),4,2)
UNION
SELECT SUBSTR(TO_CHAR(fecha,'dd/mm/rrrr'),7,4) ano,
DECODE(SUBSTR(TO_CHAR(fecha,'dd/mm/rrrr'),4,2),
'01','ENERO',
'02','FEBRERO',
'03','MARZO',
'04','ABRIL',
'05','MAYO',
'06','JUNIO',
'07','JULIO',
'08','AGOSTO',
'09','SEPTIEMBRE',
'10','OCTUBRE',
'11','NOVIEMBRE',
'12','DICIEMBRE') MES,
NVL(COUNT(*),0) TOTAL
FROM inventario
WHERE grupo = '000'
GROUP BY SUBSTR(TO_CHAR(fecha,'dd/mm/rrrr'),7,4),SUBSTR(TO_CHAR(fecha,'dd/mm/rrrr'),4,2) WITH READ ONLY;

GRANT SELECT ON "LLANTAS"."V_CONSUMOS_LLANTAS" TO "ROL_PERMISOS_TRANSER";
  GRANT SELECT ON "LLANTAS"."V_CONSUMOS_LLANTAS" TO PUBLIC;



CREATE OR REPLACE FORCE VIEW "LLANTAS"."V_LLANTAS_ACTIVAS" ("VEHICULO", "LLANTA", "GRUPO", "VALORI", "KINSTALA", "FECHAI", "FICHA", "DIMENSION", "PROFI", "FECHA", "LLANTAM", "GRUPOM", "FECHAM", "KMSM", "PROFM", "KMSH", "TOTALKMS") AS 
  (SELECT c.vehiculo vehiculo, c.llanta llanta, c.grupo grupo, c.valor valori, c.kinstala kinstala, c.fechai fechai,
  c.ficha ficha,a.dimension, trunc(((a.pi+a.pc+a.pd)/3),2) profi, c.fecha fecha, muestreo.llantam llantam, muestreo.
  grupom grupom, muestreo.fecham fecham, muestreo.kmsm kmsm, muestreo.profm profm, historia.kmsh,
  DECODE(((muestreo.kmsm - c.kinstala) + nvl(historia.kmsh,0)),null,'N/D',((muestreo.kmsm - c.kinstala) + NVL(historia.kmsh,0))) TOTALKMS
FROM llantas c, fichatec a,
     (SELECT a.llanta LLANTAM, a.grupo GRUPOM, a.kilom KMSM, a.fecha FECHAM, ((a.pi+a.pc+a.pd)/3) PROFM
       FROM muestreo a
       WHERE a.fecha = (SELECT MAX(b.fecha)
                        FROM  muestreo b
                        WHERE a.llanta = b.llanta
                        AND SUBSTR(a.grupo,3,1) = SUBSTR(b.grupo,3,1))) MUESTREO,
     (SELECT g.llanta llantah, substr(g.grupo,3,1) grupoh,  SUM(g.KREMUEVE - g.KINSTALA) kmsh
      from historia g
      GROUP BY g.llanta, substr(g.grupo,3,1)) HISTORIA
WHERE c.ficha = a.codigo
AND c.llanta = muestreo.llantam
AND SUBSTR(c.grupo,3,1) = SUBSTR(muestreo.grupom,3,1)
AND to_date(c.fechai,'dd/mm/rrrr') <> to_date(muestreo.fecham,'dd/mm/rrrr')
AND c.llanta = historia.llantah(+)
AND SUBSTR(c.grupo,3,1) = historia.grupoh(+))
;

GRANT SELECT ON "LLANTAS"."V_LLANTAS_ACTIVAS" TO "ROL_PERMISOS_TRANSER";
  GRANT SELECT ON "LLANTAS"."V_LLANTAS_ACTIVAS" TO PUBLIC;


CREATE OR REPLACE FORCE VIEW "LLANTAS"."V_LLANTAS_TOTAL" ("LLANTA", "GRUPO") AS 
  SELECT llanta,grupo
FROM historia a
WHERE (llanta,grupo) NOT IN (SELECT llanta, grupo FROM llantas)
GROUP BY llanta, grupo
UNION
SELECT llanta, grupo
FROM llantas
GROUP BY llanta, grupo
UNION
SELECT llanta, grupo
FROM inventario
GROUP BY llanta, grupo
 WITH READ ONLY;

GRANT SELECT ON "LLANTAS"."V_LLANTAS_TOTAL" TO "ROL_PERMISOS_TRANSER";
  GRANT SELECT ON "LLANTAS"."V_LLANTAS_TOTAL" TO PUBLIC;

    	